MvcFechaCumples/Models/Cumple.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace MvcFechaCumples.Models
{
    public class Cumple
    {
        public int Id { get; set; }

        [RegularExpression(@"^[A-Z]+[a-zA-Z\s]*$")]
        [Required]
        public string Nombre { get; set; }
        
        [Display(Name = "Fecha")]
        [DataType(DataType.Date)]
        public DateTime FechaCumple { get; set; }
    }
}

MvcFechaCumples/Models/ErrorViewModel.cs
using System;

namespace MvcFechaCumples.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcFechaCumples/Controllers/CumplesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcFechaCumples.Data;
using MvcFechaCumples.Models;

namespace MvcFechaCumples.Controllers
{
    public class CumplesController : Controller
    {
        private readonly MvcFechaCumplesContext _context;

        public CumplesController(MvcFechaCumplesContext context)
        {
            _context = context;
        }

        // GET: Cumples
        public async Task<IActionResult> Index()
        {
            return View(await _context.Cumple.ToListAsync());
        }

        // GET: Cumples/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cumple = await _context.Cumple
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cumple == null)
            {
                return NotFound();
            }

            return View(cumple);
        }

        // GET: Cumples/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cumples/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,FechaCumple")] Cumple cumple)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cumple);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cumple);
        }

        // GET: Cumples/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cumple = await _context.Cumple.FindAsync(id);
            if (cumple == null)
            {
                return NotFound();
            }
            return View(cumple);
        }

        // POST: Cumples/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,FechaCumple")] Cumple cumple)
        {
            if (id != cumple.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cumple);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CumpleExists(cumple.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cumple);
        }

        // GET: Cumples/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cumple = await _context.Cumple
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cumple == null)
            {
                return NotFound();
            }

            return View(cumple);
        }

        // POST: Cumples/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cumple = await _context.Cumple.FindAsync(id);
            _context.Cumple.Remove(cumple);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CumpleExists(int id)
        {
            return _context.Cumple.Any(e => e.Id == id);
        }
    }
}

MvcFechaCumples/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MvcFechaCumples.Data;
using MvcFechaCumples.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MvcFechaCumples.Controllers
{
    public class HomeController : Controller
    {
        private readonly MvcFechaCumplesContext _context;

        public HomeController(MvcFechaCumplesContext context)
        {
            _context = context;
        }

        // GET: Cumples
        public async Task<IActionResult> Index(string buscar)
        {
            var cumples = from m in _context.Cumple
                         select m;

            if (!String.IsNullOrEmpty(buscar))
            {
                cumples = cumples.Where(s => s.Nombre.Contains(buscar));
            }

            return View(await cumples.ToListAsync());
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcFechaCumples/Views/Cumples/Create.cshtml
@model MvcFechaCumples.Models.Cumple

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Cumple</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaCumple" class="control-label"></label>
                <input asp-for="FechaCumple" class="form-control" />
                <span asp-validation-for="FechaCumple" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcFechaCumples/Views/Cumples/Delete.cshtml
@model MvcFechaCumples.Models.Cumple

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cumple</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaCumple)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaCumple)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MvcFechaCumples/Views/Cumples/Details.cshtml
@model MvcFechaCumples.Models.Cumple

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Cumple</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaCumple)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaCumple)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MvcFechaCumples/Views/Cumples/Edit.cshtml
@model MvcFechaCumples.Models.Cumple

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Cumple</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaCumple" class="control-label"></label>
                <input asp-for="FechaCumple" class="form-control" />
                <span asp-validation-for="FechaCumple" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcFechaCumples/Views/Cumples/Index.cshtml
@model IEnumerable<MvcFechaCumples.Models.Cumple>

@{
    ViewData["Title"] = "Editar";
}

<h2>Editar lista de cumpleaños</h2>
<br />
<p>
    <a asp-action="Create">Agregar nuevo cumpleaños</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaCumple)
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaCumple)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>

MvcFechaCumples/Views/Home/Index.cshtml
@model IEnumerable<MvcFechaCumples.Models.Cumple>
@{
    ViewData["Title"] = "Inicio";
}

<div class="text-center">
    <h1 class="display-4">¡Hola!</h1>
    <!--<p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>-->
</div>

<h3 class="text-center">Lista de cumpleaños de amigos</h3>
<br />

<form asp-controller="Home" asp-action="Index" method="get" class="text-right">
    <p>
        <input type="text" name="Buscar" />
        <input type="submit" value="Filtrar" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaCumple)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaCumple)
                </td>
            </tr>
        }
    </tbody>
</table>

MvcFechaCumples/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cumples App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Fechas de cumples App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cumples" asp-action="Index">Editar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Acerca</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Cumples App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>